import test from 'node:test';
import assert from 'node:assert/strict';
import { validateDraft,createDraft,decodeDrafts,encodeDrafts, type DraftInput } from '../src/domain/drafts.ts';
const input: DraftInput = {category:'VTT',brand:'Yamaha',model:'Grizzly',year:'2024',mileage:'',hours:'',vin:'',condition:'Bon',notes:''};
test('valid input without VIN',()=>assert.deepEqual(validateDraft(input),[]));
test('VIN with forbidden letters rejected',()=>assert.ok(validateDraft({...input,vin:'IOQ12345678901234'}).length));
test('17-character VIN accepted',()=>assert.deepEqual(validateDraft({...input,vin:'1HGCM82633A004352'}),[]));
test('negative mileage rejected',()=>assert.ok(validateDraft({...input,mileage:'-5'}).length));
test('NaN rejected',()=>assert.ok(validateDraft({...input,hours:'NaN'}).length));
test('future year rejected',()=>assert.ok(validateDraft({...input,year:'2099'}).length));
test('missing brand rejected',()=>assert.ok(validateDraft({...input,brand:'  '}).length));
test('invalid category rejected',()=>assert.ok(validateDraft({...input,category:'???'}).length));
test('invalid condition rejected',()=>assert.ok(validateDraft({...input,condition:'???'}).length));
test('too many notes rejected',()=>assert.ok(validateDraft({...input,notes:'a'.repeat(1001)}).length));
test('new store is empty',()=>assert.deepEqual(decodeDrafts(null),[]));
test('invalid JSON rejected without resetting user data',()=>assert.throws(()=>decodeDrafts('{')));
test('unknown schema rejected',()=>assert.throws(()=>decodeDrafts('{"schemaVersion":2,"drafts":[]}')));
test('save/restore exact draft',()=>{const draft=createDraft(input);assert.deepEqual(decodeDrafts(encodeDrafts([draft])),[draft]);});
test('normalizes brand and VIN',()=>{const d=createDraft({...input,brand:' Yamaha ',vin:'1hgcm82633a004352'});assert.equal(d.brand,'Yamaha');assert.equal(d.vin,'1HGCM82633A004352');});
test('duplicates rejected',()=>{const d=createDraft(input);assert.throws(()=>encodeDrafts([d,d]));});
test('corrupt dates rejected',()=>{const d=createDraft(input);assert.throws(()=>encodeDrafts([{...d,createdAt:'broken'}]));});
